 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
       - run:
           name: "Tests"
           command: dotnet test
       - store_test_results:
           path: test-results